Update yaml structures to be compatible with k8s 1.23+
- Removed the "beta1" in apiextensios version
- Declare the field types in CustomResourceDefinition kinds.
The declaration is mandatory to apply the custom resources
in kubernetes.
- Update CRDs
- Update resources to use the new CRDs
- Add wait time for the ceph osd to create the pools. This is
necessary to generate the certificate keys properly.
- Increase number of restarts limit for job rook-ceph-provision
to give more time for the dependencies to get ready.
- Switch ceph-config-helper to ubuntu_bionic-20220802
- Update ceph to v16.2.9

Test Plan:
PASS: Apply rook-ceph-app with the changes in k8s v1.23
PASS: Apply rook-ceph-app with the changes in k8s v1.24

Story: 2009138
Task: 45647

Signed-off-by: Daian Cardoso Sganderlla <Daian.CardosoSganderlla@windriver.com>
Change-Id: Ifc1d905b49504c3ac8d1a1fd4dd3d6661661a4cd

diff --git a/stx-rook-ceph/stx-rook-ceph/helm-charts/rook-ceph-provisioner/templates/job-stx-ceph-mgr-provision.yaml b/stx-rook-ceph/stx-rook-ceph/helm-charts/rook-ceph-provisioner/templates/job-stx-ceph-mgr-provision.yaml
--- a/stx-rook-ceph/stx-rook-ceph/helm-charts/rook-ceph-provisioner/templates/job-stx-ceph-mgr-provision.yaml
+++ b/stx-rook-ceph/stx-rook-ceph/helm-charts/rook-ceph-provisioner/templates/job-stx-ceph-mgr-provision.yaml
@@ -1,6 +1,6 @@
 {{/*
 #
-# Copyright (c) 2018 Wind River Systems, Inc.
+# Copyright (c) 2018-2022 Wind River Systems, Inc.
 #
 # SPDX-License-Identifier: Apache-2.0
 #
@@ -25,6 +25,27 @@ data:
       exit 1
     fi
 
+    # Exec_retry - wait for the cluster to create osd pools
+    retries=25  # 4 minutes
+    retry_count=1
+
+    cmd="ceph osd pool ls | wc -l"
+    while [ $retry_count -le $retries ]; do
+        ret_stdout=$(eval $cmd)
+        echo "ret_stdout = " $ret_stdout
+        [ $ret_stdout -gt 1 ] && break
+
+        echo "Retry #" $retry_count
+
+        sleep 10
+        let retry_count++
+    done
+
+    if [ $retry_count -gt $retries ]; then
+      echo "Error: Ceph cluster pools not correctly initialized."
+      exit 1
+    fi
+
     cat > /tmp/controller << EOF
     [req]
     req_extensions = v3_ca
@@ -40,6 +61,28 @@ data:
     DNS.1 = controller-0
     DNS.2 = controller-1
     EOF
+
+    # Exec_retry - wait for the cluster to create osd pools
+    retries=25  # 4 minutes
+    retry_count=1
+
+    cmd="ls -1 /tmp/controller.key | wc -l"
+    while [ $retry_count -le $retries ]; do
+        ret_stdout=$(eval $cmd)
+        echo "ret_stdout = " $ret_stdout
+        [ $ret_stdout -eq 1 ] && break
+
+        echo "Retry #" $retry_count
+
+        sleep 1
+        let retry_count++
+    done
+
+    if [ $retry_count -gt $retries ]; then
+      echo "Error: File /tmp/controller.key was not created."
+      # exit 1
+    fi
+
     openssl req -new -nodes -x509 -subj /O=IT/CN=controller -days 3650 -config /tmp/controller -out /tmp/controller.crt -keyout /tmp/controller.key -extensions v3_ca
 
     for i in "a" "controller-0" "controller-1"
@@ -85,25 +128,25 @@ spec:
         - name: ceph-config
           emptyDir: {}
       initContainers:
-      - name: init
-        image: {{ .Values.images.tags.ceph_config_helper | quote }}
-        command: [ "/bin/bash", "/tmp/mount/provision.sh" ]
-        env:
-          - name: ADMIN_KEYRING
-            valueFrom:
-              secretKeyRef:
-                name: rook-ceph-admin-keyring
-                key: keyring
-          - name: ROOK_MONS
-            valueFrom:
-              configMapKeyRef:
-                name: rook-ceph-mon-endpoints
-                key: data
-        volumeMounts:
-        - mountPath: /etc/ceph
-          name: ceph-config
-        - name: config-key-provision
-          mountPath: /tmp/mount
+        - name: init
+          image: {{ .Values.images.tags.ceph_config_helper | quote }}
+          command: [ "/bin/bash", "/tmp/mount/provision.sh" ]
+          env:
+            - name: ADMIN_KEYRING
+              valueFrom:
+                secretKeyRef:
+                  name: rook-ceph-admin-keyring
+                  key: keyring
+            - name: ROOK_MONS
+              valueFrom:
+                configMapKeyRef:
+                  name: rook-ceph-mon-endpoints
+                  key: data
+          volumeMounts:
+            - mountPath: /etc/ceph
+              name: ceph-config
+            - name: config-key-provision
+              mountPath: /tmp/mount
       containers:
         - name: provision
           image: {{ .Values.images.tags.ceph_config_helper | quote }}
